apiVersion: apps/v1
kind: Deployment
metadata:
  name: etax-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etax-frontend
  template:
    metadata:
      labels:
        app: etax-frontend
    spec:
      containers:
      - name: etax-frontend
        image: docker.pkg.github.com/missprempree/etax-frontend/etax-frontend-img:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "2"
            ephemeral-storage: "500Mi"
        ports:
          - containerPort: 3000
      imagePullSecrets:
        - name: etax-frontend-pull-secret
      automountServiceAccountToken: false
      serviceAccountName: cd-yatphiroon
