- hosts: localhost

  collections:
  - kubernetes.core

  tasks:


  - name: Get a list of all pods from any namespace
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: new-project-yatphiroon
    register: pod_list


  - name: create k8s pod
    kubernetes.core.k8s:
      src: deployment.yaml
      namespace: new-project-yatphiroon
      state: present


  - name: create services
    kubernetes.core.k8s:
      src: service.yaml
      namespace: new-project-yatphiroon
      state: present

     
  - name: create route
    kubernetes.core.k8s:
      src: route.yaml
      namespace: new-project-yatphiroon
      state: present
