apiVersion: apps/v1
kind: Deployment
metadata:
  name: etax-frontend
  labels:
    app: etax-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etax-frontend
  template:
    metadata:
      labels:
        app: etax-frontend
    spec:
      containers:
      - image: docker.io/delenies/etax-frontend:latest
        name: etax-frontend
        env:
        - name: COLOR
          value: "blue"
        resources: {}
